//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloLibreFront.Traducciones.TrErrores {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrErrores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrErrores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstiloLibreFront.Traducciones.TrErrores.TrErrores", typeof(TrErrores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo obligatorio.
        /// </summary>
        public static string ERR_CampoObligatorio {
            get {
                return ResourceManager.GetString("ERR_CampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual incorrecta.
        /// </summary>
        public static string ERR_ContraseñaActualIncorrecta {
            get {
                return ResourceManager.GetString("ERR_ContraseñaActualIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña no válida. Mínimo 8 caracteres, 1 mayúscula y 1 minúscula.
        /// </summary>
        public static string ERR_ContraseñaNoValida {
            get {
                return ResourceManager.GetString("ERR_ContraseñaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coincidentes.
        /// </summary>
        public static string ERR_ContraseñasNoCoinciden {
            get {
                return ResourceManager.GetString("ERR_ContraseñasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto no encontrado.
        /// </summary>
        public static string ERR_ObjetoNoEncontrado {
            get {
                return ResourceManager.GetString("ERR_ObjetoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rellenar campos obligatorios.
        /// </summary>
        public static string ERR_RellenarCamposObligatorios {
            get {
                return ResourceManager.GetString("ERR_RellenarCamposObligatorios", resourceCulture);
            }
        }
    }
}
